'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Check,ChevronDown,ChevronRight,Search,X,History as HistoryIcon,FileText,Clock,ShieldCheck,Plus,Layers,RotateCcw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {initial,apps,type Request,type SignatureReceipt} from '@/lib/demo-data';
import Correspondence,{DocumentJourney} from './correspondence';
import QuickSummary from './quick-summary';
import Signing from './signing';
import WorkflowAudit from './workflow-audit';
import {decisionEvent} from '@/lib/demo-audit';
import ContextAssistant from './context-assistant';
import SourceAttachments from './source-attachments';
const questions=['Check the budget','What changed?','Show the risks'];
type Lens='overview'|'budget'|'changes'|'risk';
function Evidence({children}:{children:React.ReactNode}){return <div className="evidence"><span/> {children} <span className="sample">Sample evidence</span></div>}
function Purchase({r,lens}:{r:Request,lens:Lens}){const infrastructure=r.id==='PR-2026-0842';if(!infrastructure)return <General r={r}/>;return <>
<div className="context-intro"><span className="section-index">01 / FINANCIAL CONTEXT</span><div className="context-title"><h2>A purchase with room<br/>in the budget.</h2><div className="big-amount"><span>REQUESTED AMOUNT</span><strong><small>QAR</small> 148,500</strong></div></div></div>
<div className={'budget-surface '+(lens==='budget'?'focused':'')} id="budget-evidence"><div className="budget-top"><span>IT infrastructure · Available budget</span><b>QAR 240,000</b></div><div className="budget-bar" aria-label="Request uses 61.9 percent of available budget"><div style={{width:'61.875%'}}/><span/></div><div className="budget-legend"><span><i/>This request <b>148,500</b></span><span><i/>Remaining <b>91,500</b></span></div>{lens==='budget'&&<div className="expanded-evidence"><h3>Within the available allocation</h3><p>QAR 240,000 − QAR 148,500 = <b>QAR 91,500 remaining.</b> This uses 61.9% of the sample available budget. Other unposted commitments are not included.</p></div>}<Evidence>SAP S/4HANA · Cost center IT-2040</Evidence></div>
<div className="two-columns"><section><div className="section-line"><h3>What you’re approving</h3><span>3 line items</span></div><Table><TableHeader><TableRow><TableHead>ITEM</TableHead><TableHead>QTY</TableHead><TableHead className="text-right">QAR</TableHead></TableRow></TableHeader><TableBody>{[['Network switches','6','54,000'],['Rack servers','2','78,000'],['Installation & setup','1','16,500']].map(v=><TableRow key={v[0]}>{v.map((c,i)=><TableCell className={i===2?'text-right':''} key={c}>{c}</TableCell>)}</TableRow>)}</TableBody></Table><Evidence>Purchase requisition · PR-2026-0842</Evidence></section><section className="vendor"><span className="section-index">SELECTED VENDOR</span><h3>Gulf Business Machines</h3><p>Network and server upgrades<br/>for the Lusail office expansion.</p><div className="vendor-fact"><span>Delivery</span><b>Lusail office</b></div><div className="vendor-fact"><span>Comparison quotes</span><b className="amber-text">Not provided</b></div></section></div>
{lens==='changes'&&<div className="insight amber"><h3>No previous version is available</h3><p>This sample contains the current requisition only. A change comparison needs the prior source version; no changes can be verified here.</p></div>}
{lens==='risk'&&<div className="insight amber"><h3>Two things to verify</h3><p>The available budget covers the request, but competing quotes and unposted commitments are not included in the sample. Confirm those in the live procurement workflow before a real approval.</p></div>}
</>}
function Leave({lens}:{lens:Lens}){return <><div className="context-intro"><span className="section-index">01 / PEOPLE & COVERAGE</span><div className="context-title"><h2>Five days away.<br/>A team with a plan.</h2><div className="big-amount"><span>13–17 SEPTEMBER</span><strong>05 <small>workdays</small></strong></div></div></div><div className="leave-layout"><section className="calendar"><div className="section-line"><h3>September 2026</h3><span>Sunday–Thursday workweek</span></div><div className="calendar-grid">{['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d=><span className="weekday" key={d}>{d}</span>)}{Array.from({length:35},(_,i)=>{const d=i-1;return <span className={(d>=13&&d<=17?'leave-day ':'')+(i%7>=5?'weekend':'')} key={i}>{d>0&&d<=30?d:''}</span>})}</div><div className="calendar-key"><i/>Requested annual leave</div><Evidence>SuccessFactors · LV-2026-0318</Evidence></section><section className="coverage"><span className="section-index">LEAVE BALANCE</span><strong>18 <small>→</small> 13 <em>days</em></strong><p>Balance after this request</p><div className="coverage-person"><span className="avatar">MA</span><div><b>Mariam Ali</b><small>Named covering colleague</small></div></div><p className="fine">Coverage is stated in the request. Colleague acceptance has not been independently verified.</p></section></div>{lens==='changes'?<div className="insight"><h3>Current dates: 13–17 September</h3><p>No earlier version is included, so changes to the dates or coverage cannot be verified.</p></div>:<div className={'insight '+(lens==='risk'?'amber':'')}><h3>{lens==='risk'?'Check team availability before deciding':'The coverage picture'}</h3><p>Mariam is named as cover. Team leave overlaps and staffing levels are not provided in this sample, so coverage is not automatically marked as confirmed.</p></div>}</>}
function Document({lens}:{lens:Lens}){return <><div className="context-intro"><span className="section-index">01 / DOCUMENT REVIEW</span><div className="context-title"><h2>The agreement.<br/>And the details that matter.</h2><div className="big-amount"><span>ANNUAL CONTRACT VALUE</span><strong><small>QAR</small> 320,000</strong></div></div></div><div className="document-layout"><article className="document-page"><div className="doc-letterhead">PIH <span>LEGAL & COMPLIANCE</span></div><div className="document-label">ILLUSTRATIVE EXCERPT · NOT A SIGNABLE DOCUMENT</div><h3>Facilities Services<br/>Agreement</h3><p className="doc-parties">Power International Holding<br/>& Al Jaber Facilities</p><hr/><h4>01. Scope of services</h4><p>Facilities services for the designated PIH premises, subject to the approved scope and service schedule.</p><h4>02. Term & consideration</h4><p>The agreement term is <mark>12 months</mark>, with an annual contract value of <mark>QAR 320,000</mark>.</p><h4>03. Execution</h4><p>Authorized signatories must complete the signing process in Signature.ai.</p><div className="doc-bottom">REVIEW COPY<span>01 / 01</span></div></article><section className="document-notes"><span className="section-index">REVIEW NOTES</span><div><ShieldCheck size={20}/><h3>Legal review completed</h3><p>Recorded in the sample request. Supporting legal comments are not attached.</p></div><div><FileText size={20}/><h3>{lens==='changes'?'No prior version to compare':'Full agreement required'}</h3><p>{lens==='changes'?'A verified redline needs both source document versions. This excerpt does not establish what changed.':'This is a sample excerpt, not the original contract. Review the complete source document before execution.'}</p></div><div className={lens==='risk'?'risk-highlight':''}><Clock size={20}/><h3>Your electronic signature is required</h3><p>Prior approvals are complete in this sample. Review & sign lets you choose a signature appearance and confirm the signing step.</p></div></section></div><Evidence>Signature.ai · DOC-2026-0156 · Illustrative excerpt</Evidence></>}
function General({r}:{r:Request}){const headings:Record<number,string>={0:'The purchase, in context.',1:'An investment in your people.',3:'The right access.\nFor the right work.',4:'A journey with\na clear purpose.',5:'A small pilot.\nA deliberate decision.'};return <><div className="context-intro"><span className="section-index">01 / {apps[r.app].category.toUpperCase()}</span><div className="context-title"><h2 style={{whiteSpace:'pre-line'}}>{headings[r.app]}</h2><div className="big-amount"><span>REQUEST SCOPE</span><strong className="smaller-amount">{r.amount}</strong></div></div></div><div className="facts-grid">{Object.entries(r.fields).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="insight"><h3>{r.app===3?'Access context':r.app===5?'Pilot boundaries':'Before you decide'}</h3><p>{r.description}</p><p className="fine">Only the fields supplied with this sample request are shown. Additional policy evidence and source documents are not available.</p></div><Evidence>{apps[r.app].name} · {r.id}</Evidence></>}
export default function Home(){const [signing,setSigning]=useState(false);useEffect(()=>{if(signing)document.querySelector('.canvas')?.scrollIntoView({block:'start'})},[signing]);const [mode,setMode]=useState('quick');const [embedded,setEmbedded]=useState(false);useEffect(()=>{setEmbedded(window.self!==window.top)},[]);function changeMode(value:string){setMode(value)}const [requests,setRequests]=useState(initial);const [active,setActive]=useState(initial[0].id);const [view,setView]=useState('Decisions');const [query,setQuery]=useState('');const [urgent,setUrgent]=useState(false);const [lens,setLens]=useState<Lens>('overview');const [queueOpen,setQueueOpen]=useState(true);const [note,setNote]=useState('');const [returnOpen,setReturnOpen]=useState(false);const [notice,setNotice]=useState('');const [appFilter,setAppFilter]=useState<number|null>(null);const [info,setInfo]=useState<number|null>(null);
useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timeout)},[notice]);
const r=requests.find(r=>r.id===active)!;const pending=requests.filter(r=>r.status==='Pending');const done=requests.filter(r=>r.status!=='Pending');const rows=(view==='History'?done:pending).filter(r=>(appFilter===null||r.app===appFilter)&&(!urgent||r.priority==='High')&&`${r.title} ${r.name} ${r.id} ${apps[r.app].name}`.toLowerCase().includes(query.toLowerCase()));
function choose(id:string){setMode('quick');setSigning(false);if(window.matchMedia('(max-width:700px)').matches)window.scrollTo({top:0});else document.querySelector('.workspace')?.scrollIntoView({block:'start'});setActive(id);setLens('overview');setQueueOpen(false)}
function focusEvidence(q:string){setLens(/chang|version|redline/i.test(q)?'changes':/risk|policy|cover/i.test(q)?'risk':'budget')}
function backToQueue(){setSigning(false);setQueueOpen(true);if(window.matchMedia('(max-width:700px)').matches)window.scrollTo({top:0})}
function afterDecision(){if(window.matchMedia('(max-width:700px)').matches)backToQueue()}
function recordSignature(receipt:SignatureReceipt){if(r.action!=='sign'||r.status!=='Pending')return;const event=decisionEvent(r,'Signed','',receipt.method);setRequests(prev=>prev.map(x=>x.id===r.id?{...x,status:'Signed',signatureReceipt:receipt,audit:[...x.audit,event]}:x));setSigning(false);setNotice(`${r.id} signed in this demo. Audit updated.`);afterDecision()}
function decide(status:string){if(status==='Approved'&&r.action==='sign')return;if(status==='Returned'&&!note.trim())return;if(r.status!=='Pending')return;const event=decisionEvent(r,status,note.trim());setRequests(prev=>prev.map(x=>x.id===r.id?{...x,status,decisionNote:note.trim(),audit:[...x.audit,event]}:x));setNotice(`${r.id} ${status.toLowerCase()} in this demo session.`);setReturnOpen(false);setNote('');afterDecision()}
const chips=r.app===1?['Check leave balance','What changed?','Check team coverage']:r.app===2?['Review contract value','What changed?','Show the risks']:questions;
return <div className={'decision-app '+'quick-mode'+(mode==='rich'?' request-context-open':'')+(queueOpen?' queue-is-open':'')+(signing?' signing-active':'')}><header className="masthead"><a className="wordmark" href="/" aria-label="PIH home">pih<span>▪</span></a><span className="product-name">Decision<br/><b>workspace</b></span><Tabs value={view} onValueChange={v=>{setSigning(false);setView(String(v));setQuery('');setAppFilter(null);setUrgent(false);if(v==='History'&&done.length)choose(done[0].id);if(v==='Decisions'&&pending.length)choose(pending[0].id);backToQueue()}}><TabsList variant="line">{['Decisions','Correspondence','History','Applications'].map(v=><TabsTrigger key={v} value={v}>{v}{v==='Decisions'&&<span className="nav-number">{pending.length}</span>}</TabsTrigger>)}</TabsList></Tabs><div className="masthead-right">{!embedded&&<a className="masthead-preview-link" href="/mobile-preview">Mobile preview <ArrowUpRight size={14}/></a>}<span className="demo-pill">DEMO · 07</span><span className="avatar">JA</span></div></header>
<div hidden={view!=='Correspondence'}><Correspondence documentStatus={requests.find(x=>x.app===2)?.status||'Pending'}/></div>{view==='Correspondence'?null:view==='Applications'?<main className="applications"><span className="overline">THE CONNECTED WORKSPACE</span><h1>One place.<br/><em>Every kind of decision.</em></h1><p className="applications-intro">Each application brings its own context. Your approval experience stays connected.</p><div className="application-grid">{apps.map((a,i)=><button key={a.name} onClick={()=>setInfo(i)}><span className="app-monogram" style={{color:a.color}}>{a.short}</span><h2>{a.name}</h2><p>{a.category}</p><div><span>{pending.filter(r=>r.app===i).length} waiting</span><ArrowUpRight size={21}/></div><small>Sample adapter · Not connected</small></button>)}</div><div className="connector-footer"><Layers/><div><h2>Ready for what comes next.</h2><p>A shared connector contract provides a foundation for future web and mobile integrations.</p></div></div></main>:<><section className="briefing"><div><span className="overline">YOUR FOCUS / 04 SEPTEMBER 2026 · SAMPLE SNAPSHOT</span><h1 className="desktop-brief-title">{view==='History'?<>Your decisions.</>:<>Ready for your decision.</>}</h1><h1 className="mobile-brief-title">{view==='History'?'Your decisions.':queueOpen?'Your request queue.':'Your decision.'}</h1></div><div className="briefing-context"><span className="tiny-line"/><p><b>{view==='History'?done.length:pending.length} decisions</b> {view==='History'?'completed this session':'waiting for you'}<span className="quick-brief-extra"> · {new Set(pending.map(r=>r.app)).size} applications</span></p><span className="briefing-caption">YOUR JUDGMENT. ALL THE CONTEXT.</span></div></section>
<div className="mobile-queue-toggle"><button onClick={backToQueue}><ArrowLeft size={18}/> {view==='History'?'Back to history':'Back to request queue'} <span>{rows.length}</span></button></div>
<div className="workspace"><aside className={'queue '+(queueOpen?'queue-open':'')}><div className="queue-heading"><span>{view==='History'?'COMPLETED · THIS SESSION':'REQUEST QUEUE'}</span><b>{rows.length.toString().padStart(2,'0')}</b></div><label className="queue-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a request" aria-label="Find a request"/></label><div className="queue-filters"><button className={!urgent?'selected':''} onClick={()=>setUrgent(false)}>All requests</button><button className={urgent?'selected':''} onClick={()=>setUrgent(true)}>Priority</button>{appFilter!==null&&<button onClick={()=>setAppFilter(null)}>Clear source <X size={12}/></button>}</div><div className="queue-items">{rows.map((item,i)=><button key={item.id} className={'queue-item '+(active===item.id?'current':'')} onClick={()=>choose(item.id)}><div className="queue-meta"><span>{apps[item.app].name}</span><small>{item.status==='Pending'?(item.priority==='High'?'● Priority':'Pending'):item.status}</small></div><h3>{item.title}</h3><p>{item.name}</p><div className="queue-bottom"><span>{item.amount}</span><ArrowUpRight size={16}/></div>{item.due.includes('Overdue')&&item.status==='Pending'&&<span className="queue-overdue">Overdue · sample snapshot</span>}</button>)}{rows.length===0&&<div className="queue-empty"><Check size={23}/><p>{view==='History'?'Your completed decisions and their audit trails will appear here.':pending.length===0?'You’re all caught up. Your decisions and audit trails are in History.':'No requests match your filters.'}</p></div>}</div><div className="queue-foot"><span className="live-dot"/>6 sample applications · Tap a request to review</div></aside>
{view==='History'&&done.length===0?<section className="blank-canvas"><Check size={38}/><h2>A clean slate.</h2><p>Approve or return a request to start your session history.</p></section>:<main className="canvas" aria-label="Request details" key={r.id}>{signing?<Signing request={r} onCancel={()=>setSigning(false)} onSigned={recordSignature}/>:<><div className="request-kicker"><span>{apps[r.app].name}<span className="slash">/</span>{r.documentType}<span className="slash">/</span>{r.id}</span><span className={'status-tag '+(r.status==='Pending'?'':'completed')}>{r.status==='Pending'?<Clock size={13}/>:<Check size={13}/>} {r.status==='Pending'?r.due:r.status}</span></div><div className="request-heading"><h2>{r.title}</h2><p><span className="mini-avatar">{r.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>Requested by <b>{r.name}</b><span className="dot-sep">·</span>{r.department}</p></div><button className="audit-jump" onClick={()=>document.getElementById('workflow-audit')?.scrollIntoView({block:'start',behavior:'smooth'})}><HistoryIcon size={15}/> Workflow audit <span>{r.audit.length} events{r.audit.some(e=>e.actor.kind==='agent')?' · Includes agent work':''}</span><ChevronDown size={14}/></button>{mode==='quick'?<><QuickSummary request={r} onContext={()=>changeMode('rich')}/><SourceAttachments request={r}/></>:<><div className="request-viewbar"><button onClick={()=>changeMode('quick')}><ArrowLeft size={15}/> Back to Quick view</button><span>FULL CONTEXT · THIS REQUEST</span></div><SourceAttachments request={r}/><div className="context-summary"><span className="summary-mark">✳</span><p>{r.description}</p></div>
<section className="context-controls"><div className="context-controls-top"><span><Layers size={15}/> Explore the context</span><span>GUIDED DEMO</span></div><div className="question-chips">{chips.map((q,i)=><button key={q} className={lens===(['budget','changes','risk'][i])?'chosen':''} onClick={()=>focusEvidence(q)}>{q}<ArrowUpRight size={14}/></button>)}{lens!=='overview'&&<button className="reset-lens" onClick={()=>{setLens('overview')}} aria-label="Reset context"><RotateCcw size={14}/></button>}</div></section>
{r.app===2&&<DocumentJourney status={r.status} requiresSignature={r.action==='sign'}/>}<div className="adaptive-surface" key={lens}>{r.id===initial[1].id?<Leave lens={lens}/>:r.app===2?<Document lens={lens}/>:r.app===0?<Purchase r={r} lens={lens}/>:<General r={r}/>}</div></>}
<ContextAssistant request={r}/>{r.signatureReceipt&&<div className="signature-receipt"><Check size={19}/><div><h3>Signed in this demo</h3><p>{r.signatureReceipt.method} · {r.signatureReceipt.name}</p><small>{r.signatureReceipt.version} · {new Date(r.signatureReceipt.signedAt).toLocaleString()}</small><p>Awaiting a real Signature.ai integration. No document was executed or dispatched.</p></div></div>}{r.decisionNote&&<div className="insight"><h3>Your decision note</h3><p>{r.decisionNote}</p></div>}<WorkflowAudit request={r}/>
<div className="action-bar"><div><span className="action-caption">{r.status==='Pending'?'READY WHEN YOU ARE':'DECISION RECORDED'}</span><p>{r.status==='Pending'?'One request at a time.':'Saved for this demo session only.'}</p></div><div className="action-buttons">{r.status==='Pending'?<><button className="return-button" onClick={()=>setReturnOpen(true)}>Return <ArrowLeft size={15}/></button><button className="approve-button" onClick={()=>r.action==='sign'?setSigning(true):decide('Approved')}>{r.action==='sign'?'Review & sign':'Approve request'}<ArrowRight size={17}/></button></>:<><button className="approve-button mobile-completed-queue" onClick={()=>{setView('Decisions');setQuery('');setAppFilter(null);setUrgent(false);backToQueue()}}>Back to request queue <ArrowLeft size={17}/></button><button className="approve-button desktop-next-decision" onClick={()=>{const next=pending.find(x=>x.id!==r.id);if(next){setView('Decisions');choose(next.id)}else{setView('History')}}}>{pending.length?'Next decision':'View history'}<ArrowRight size={17}/></button></>}</div></div><p className="demo-footer">Sample data. Decisions stay in this session; no source-system action or digital signature is performed.</p>
</>}</main>}</div></>}
<Sheet open={returnOpen} onOpenChange={setReturnOpen}><SheetContent className="return-sheet"><SheetHeader><SheetTitle>Give the requester a clear next step.</SheetTitle><SheetDescription>Return {r.id} with a reason.</SheetDescription></SheetHeader><div className="return-form"><label htmlFor="return-note">What needs to change?</label><textarea id="return-note" placeholder="Explain what’s missing or needs another look…" value={note} onChange={e=>setNote(e.target.value)}/><button className="approve-button" disabled={!note.trim()} onClick={()=>decide('Returned')}>Return request <ArrowRight size={17}/></button><p>Demo decision only. This note is not sent to the requester.</p></div></SheetContent></Sheet>
<Sheet open={info!==null} onOpenChange={o=>{if(!o)setInfo(null)}}><SheetContent className="return-sheet"><SheetHeader><SheetTitle>{info!==null&&apps[info].name}</SheetTitle><SheetDescription>Sample adapter · Live connection not configured</SheetDescription></SheetHeader><div className="return-form"><h3>Context, shaped by the request.</h3>{info===0&&<p className="sap-types"><b>SAP S/4HANA approval types</b><span>Purchase requisitions (PR)</span><span>Purchase orders (PO)</span><span>Comparative bid summaries (CBS)</span></p>}<p>The connector supplies request fields, assigned approvers and allowed actions. The workspace selects the relevant decision surface.</p><h3>Production connection</h3><p>PIH identity, source credentials, permission checks, version reconciliation and a durable audit trail still need to be implemented.</p><button className="approve-button" onClick={()=>{const next=pending.find(r=>r.app===info);setView('Decisions');setAppFilter(info);setUrgent(false);setQuery('');if(next)choose(next.id);backToQueue();setInfo(null)}}>View requests <ArrowRight size={16}/></button></div></SheetContent></Sheet>
{notice&&<div className="notice" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
</div>}
