import {ArrowUpRight,ChevronRight} from 'lucide-react';
import type {Request} from '@/lib/demo-data';

type QuickContext = {summary:string;facts:[string,string][];gap:string;detail:string};
const context:Record<string,QuickContext>={
 'PR-2026-0842':{summary:'Network and server upgrades for the Lusail office expansion.',facts:[['Vendor','Gulf Business Machines'],['Budget after approval','QAR 91,500 remaining'],['Cost center','IT-2040']],gap:'Comparison quotes and unposted commitments are not supplied.',detail:'See budget & line items'},
 'LV-2026-0318':{summary:'Annual leave, with Mariam Ali named as cover.',facts:[['Dates','13–17 September 2026'],['Balance after leave','13 days'],['Covering colleague','Mariam Ali']],gap:'Team overlaps and cover acceptance have not been verified.',detail:'See calendar & coverage'},
 'DOC-2026-0156':{summary:'Facilities agreement ready for your electronic signature in Signature.ai.',facts:[['Counterparty','Al Jaber Facilities'],['Value / term','QAR 320,000 · 12 months'],['Prior approvals','Completed in sample']],gap:'Only an illustrative excerpt is available. Full agreement review is still required.',detail:'Review document & journey'},
};
export default function QuickSummary({request:r,onContext}:{request:Request;onContext:()=>void}){const c=context[r.id]||{summary:r.description,facts:Object.entries(r.fields).slice(0,3) as [string,string][],gap:'Additional policy evidence and source documents are not included in this sample.',detail:'See supporting context'};return <section className="quick-summary" aria-label="Decision essentials"><div className="quick-scope"><span>{r.status==='Signed'?'SIGNATURE':'REQUESTED'}</span><strong>{r.status==='Signed'?'Signed in demo':r.amount}</strong></div><p className="quick-description">{r.status==='Signed'?'Your signature choice has been recorded for this demo. No original document was executed.':c.summary}</p><dl className="quick-facts">{c.facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="quick-gap"><span>Keep in mind</span><p>{c.gap}</p></div><button className="reveal-context" onClick={onContext}><span>Full context <small>{c.detail}</small></span><ArrowUpRight size={17}/></button></section>}
