import type {WorkflowEvent} from './workflow-audit';
import {sampleAudit} from './demo-audit';
export type SignatureReceipt={method:string;name:string;signedAt:string;version:string};
export type SourceAttachment={id:string;name:string;label:string;kind:'PDF'|'XLSX'|'DOCX';size:string;source:string;uploadedAt:string;uploadedBy:string;version:string;preview:{eyebrow:string;title:string;summary:string;facts:[string,string][];columns:string[];rows:string[][]}};
export type Request={audit:WorkflowEvent[];attachments:SourceAttachment[];documentType:string;id:string;title:string;app:number;name:string;department:string;amount:string;due:string;priority:string;description:string;fields:Record<string,string>;status:string;decisionNote?:string;action?:'approve'|'sign';signatureReceipt?:SignatureReceipt};
export const apps=[{name:'SAP S/4HANA',short:'SAP',color:'#1479b8',category:'Finance & procurement'},{name:'SuccessFactors',short:'SF',color:'#268ac1',category:'People & HR'},{name:'Signature.ai',short:'S.',color:'#7451cb',category:'Documents & signatures'},{name:'IT Service Desk',short:'IT',color:'#d08a25',category:'Technology & access'},{name:'Tamas',short:'T',color:'#187d74',category:'Business operations'},{name:'AI Applications',short:'AI',color:'#b45786',category:'AI & automation'}];
const pdf=(id:string,name:string,label:string,title:string,summary:string,facts:[string,string][],rows:string[][]=[]):SourceAttachment=>({id,name,label,kind:'PDF',size:rows.length?'1.2 MB':'284 KB',source:'SAP S/4HANA · Sample attachment service',uploadedAt:'02 Sep 2026 · 08:56 Qatar time',uploadedBy:'Ahmed Al-Kuwari',version:'Source version 1',preview:{eyebrow:label.toUpperCase(),title,summary,facts,columns:rows.length?['Item','Qty','QAR']:[],rows}});
const xlsx=(id:string,name:string,label:string,title:string,summary:string,facts:[string,string][],columns:string[],rows:string[][]):SourceAttachment=>({id,name,label,kind:'XLSX',size:'92 KB',source:'SAP S/4HANA · Sample attachment service',uploadedAt:'02 Sep 2026 · 08:58 Qatar time',uploadedBy:'Procurement Operations',version:'Source version 3',preview:{eyebrow:label.toUpperCase(),title,summary,facts,columns,rows}});
const sampleRequests:Omit<Request,'audit'>[]=[
{id:'PR-2026-0842',documentType:'PR',title:'Purchase requisition · IT infrastructure upgrade',app:0,name:'Ahmed Al-Kuwari',department:'Information Technology',amount:'QAR 148,500',due:'Overdue by 1 day',priority:'High',description:'Purchase requisition for network equipment and server upgrades at the Lusail office.',fields:{'Vendor':'Gulf Business Machines','Cost center':'IT-2040 · Infrastructure','Budget available':'QAR 240,000','Delivery location':'PIH, Lusail office'},attachments:[pdf('a1','PR-2026-0842.pdf','Purchase requisition','IT infrastructure upgrade','Purchase requisition submitted for the Lusail office expansion.',[['Request total','QAR 148,500'],['Cost center','IT-2040'],['Delivery','Lusail office']],[['Network switches','6','54,000'],['Rack servers','2','78,000'],['Installation','1','16,500']]),pdf('a2','GBM_Quote_QT-8841.pdf','RFQ supplier quotation','Quotation QT-8841','Commercial quotation from Gulf Business Machines.',[['Quoted total','QAR 148,500'],['Validity','30 days'],['Payment','30 days']],[['Network switches','6','54,000'],['Rack servers','2','78,000'],['Installation','1','16,500']]),xlsx('a3','Network_Upgrade_Scope.xlsx','Technical scope','Network upgrade scope','Technical requirements and delivery milestones.',[['Location','Lusail'],['Owner','IT Infrastructure']],['Milestone','Owner','Target'],[['Equipment delivery','Vendor','Week 1'],['Installation','Vendor + PIH','Week 2'],['Acceptance','PIH IT','Week 3']])],status:'Pending'},
{id:'LV-2026-0318',documentType:'Leave',title:'Annual leave request',app:1,name:'Sara Hassan',department:'Human Resources',amount:'5 working days',due:'Due today',priority:'Normal',description:'Annual leave from 13–17 September 2026. Coverage has been arranged with the HR operations team.',fields:{'Leave dates':'13–17 September 2026','Leave balance':'18 days','Covering colleague':'Mariam Ali'},attachments:[],status:'Pending'},
{id:'DOC-2026-0156',documentType:'Agreement',title:'Vendor service agreement',app:2,action:'sign',name:'Omar Ibrahim',department:'Legal & Compliance',amount:'Signature required',due:'Due today',priority:'High',description:'Review and electronically sign the annual facilities services agreement. Prior approvals and legal review are complete in this sample.',fields:{'Counterparty':'Al Jaber Facilities','Contract term':'12 months','Contract value':'QAR 320,000','Legal review':'Completed','Approval stage':'Completed (sample)'},attachments:[{...pdf('d1','Facilities_Services_Agreement.pdf','Agreement','Facilities Services Agreement','Execution copy prepared for authorized electronic signature.',[['Counterparty','Al Jaber Facilities'],['Term','12 months'],['Value','QAR 320,000']]),source:'Signature.ai · Sample document service',uploadedBy:'Omar Ibrahim'}],status:'Pending'},
{id:'IT-2026-1294',documentType:'Access',title:'Adobe Creative Cloud access',app:3,name:'Fatima Al-Mansoori',department:'Marketing',amount:'QAR 2,640 / year',due:'Due tomorrow',priority:'Normal',description:'An annual Creative Cloud license is required for the new brand and communications designer.',fields:{'License':'Creative Cloud for teams','Duration':'12 months','Manager review':'Completed'},attachments:[],status:'Pending'},
{id:'TM-2026-0621',documentType:'Travel',title:'Business travel to Riyadh',app:4,name:'Khalid Abdullah',department:'Business Development',amount:'QAR 8,200',due:'Due tomorrow',priority:'Normal',description:'Travel authorization for client meetings in Riyadh from 8–10 September, including flights and accommodation.',fields:{'Destination':'Riyadh, Saudi Arabia','Travel dates':'8–10 September 2026','Purpose':'Client meetings'},attachments:[],status:'Pending'},
{id:'AI-2026-0047',documentType:'AI access',title:'Procurement copilot · pilot access',app:5,name:'Mariam Ali',department:'Procurement',amount:'12 team members',due:'Due in 3 days',priority:'Normal',description:'Approve a limited pilot of the procurement copilot for twelve team members using the approved procurement knowledge base.',fields:{'Pilot duration':'30 days','Data scope':'Approved procurement documents','Security review':'Completed'},attachments:[],status:'Pending'},
{id:'PO-2026-0931',documentType:'PO',title:'Purchase order · Office furniture',app:0,name:'Yousef Ahmed',department:'Administration',amount:'QAR 42,750',due:'Due in 3 days',priority:'Normal',description:'Purchase order for furniture for the new project management office.',fields:{'Vendor':'Al Mana Interiors','Cost center':'ADM-1020','Budget available':'QAR 75,000'},attachments:[pdf('p1','PO-2026-0931.pdf','Purchase order','Office furniture purchase order','Purchase order prepared for Al Mana Interiors.',[['PO total','QAR 42,750'],['Cost center','ADM-1020'],['Terms','30 days']],[['Work desks','12','18,000'],['Office chairs','12','12,750'],['Meeting tables','3','12,000']]),pdf('p2','Al_Mana_Quotation.pdf','Supplier quotation','Furniture quotation','Selected supplier quotation and delivery terms.',[['Quoted total','QAR 42,750'],['Delivery','21 days'],['Warranty','2 years']]),xlsx('p3','CBS-2026-0198.xlsx','Comparative bid summary','Furniture bid comparison','Commercial comparison used to select Al Mana Interiors.',[['Recommended','Al Mana Interiors'],['Evaluation','Commercial + delivery']],['Bidder','Total','Delivery'],[['Al Mana Interiors','42,750','21 days'],['Doha Office Co.','45,900','14 days'],['Workspace Qatar','47,200','18 days']])],status:'Pending'},
{id:'CBS-2026-0204',documentType:'CBS',title:'Comparative bid summary · Generator maintenance',app:0,name:'Layla Al-Thani',department:'Facilities & Procurement',amount:'QAR 620,000',due:'Due in 4 days',priority:'Normal',description:'Comparative bid summary for annual generator maintenance across PIH facilities.',fields:{'Recommended bidder':'Gulf Technical Services','Bids received':'3 compliant bids','Evaluation':'70% technical · 30% commercial','Savings vs next bid':'QAR 34,000'},attachments:[xlsx('c1','CBS-2026-0204.xlsx','Comparative bid summary','Generator maintenance bid comparison','Technical and commercial comparison of three compliant bids.',[['Recommended','Gulf Technical Services'],['Award value','QAR 620,000']],['Bidder','Technical','Total'],[['Gulf Technical Services','91%','620,000'],['Prime Power Qatar','88%','654,000'],['Doha Engineering','84%','672,500']]),pdf('c2','Quote_GTS-2219.pdf','RFQ supplier quotation','Gulf Technical Services','Recommended commercial and technical offer.',[['Offer','QAR 620,000'],['Technical score','91%'],['Validity','45 days']]),pdf('c3','Quote_PPQ-883.pdf','RFQ supplier quotation','Prime Power Qatar','Second-ranked compliant offer.',[['Offer','QAR 654,000'],['Technical score','88%'],['Validity','30 days']]),pdf('c4','Quote_DE-492.pdf','RFQ supplier quotation','Doha Engineering','Third-ranked compliant offer.',[['Offer','QAR 672,500'],['Technical score','84%'],['Validity','30 days']])],status:'Pending'},
{id:'HR-2026-0214',documentType:'Learning',title:'Learning & development request',app:1,name:'Noor Mohammed',department:'Finance',amount:'QAR 4,800',due:'Due in 4 days',priority:'Normal',description:'Enrollment in a financial planning and analysis certification program.',fields:{'Course':'Financial Planning & Analysis','Provider':'Corporate Finance Institute','Duration':'6 weeks'},attachments:[],status:'Pending'}];
export const initial:Request[]=sampleRequests.map(r=>({...r,audit:sampleAudit(r)}));
