export type Request={id:string;title:string;app:number;name:string;department:string;amount:string;due:string;priority:string;description:string;fields:Record<string,string>;status:string;decisionNote?:string};
export const apps=[{name:'SAP S/4HANA',short:'SAP',color:'#1479b8',category:'Finance & procurement'},{name:'SuccessFactors',short:'SF',color:'#268ac1',category:'People & HR'},{name:'Signature.ai',short:'S.',color:'#7451cb',category:'Documents & signatures'},{name:'IT Service Desk',short:'IT',color:'#d08a25',category:'Technology & access'},{name:'Tamas',short:'T',color:'#187d74',category:'Business operations'},{name:'AI Applications',short:'AI',color:'#b45786',category:'AI & automation'}];
export const initial:Request[]=[
{id:'PR-2026-0842',title:'IT infrastructure upgrade',app:0,name:'Ahmed Al-Kuwari',department:'Information Technology',amount:'QAR 148,500',due:'Overdue by 1 day',priority:'High',description:'Purchase request for network equipment and server upgrades at the Lusail office. The upgrade will support the new office expansion and improve network reliability.',fields:{'Vendor':'Gulf Business Machines','Cost center':'IT-2040 · Infrastructure','Budget available':'QAR 240,000','Delivery location':'PIH, Lusail office'},status:'Pending'},
{id:'LV-2026-0318',title:'Annual leave request',app:1,name:'Sara Hassan',department:'Human Resources',amount:'5 working days',due:'Due today',priority:'Normal',description:'Annual leave from 13–17 September 2026. Coverage has been arranged with the HR operations team.',fields:{'Leave dates':'13–17 September 2026','Leave balance':'18 days','Covering colleague':'Mariam Ali'},status:'Pending'},
{id:'DOC-2026-0156',title:'Vendor service agreement',app:2,name:'Omar Ibrahim',department:'Legal & Compliance',amount:'Signature required',due:'Due today',priority:'High',description:'Review and authorize the annual facilities services agreement before the final signing stage. Legal has completed its review.',fields:{'Counterparty':'Al Jaber Facilities','Contract term':'12 months','Contract value':'QAR 320,000','Legal review':'Completed'},status:'Pending'},
{id:'IT-2026-1294',title:'Adobe Creative Cloud access',app:3,name:'Fatima Al-Mansoori',department:'Marketing',amount:'QAR 2,640 / year',due:'Due tomorrow',priority:'Normal',description:'An annual Creative Cloud license is required for the new brand and communications designer.',fields:{'License':'Creative Cloud for teams','Duration':'12 months','Manager review':'Completed'},status:'Pending'},
{id:'TM-2026-0621',title:'Business travel to Riyadh',app:4,name:'Khalid Abdullah',department:'Business Development',amount:'QAR 8,200',due:'Due tomorrow',priority:'Normal',description:'Travel authorization for client meetings in Riyadh from 8–10 September, including flights and accommodation.',fields:{'Destination':'Riyadh, Saudi Arabia','Travel dates':'8–10 September 2026','Purpose':'Client meetings'},status:'Pending'},
{id:'AI-2026-0047',title:'Procurement copilot · pilot access',app:5,name:'Mariam Ali',department:'Procurement',amount:'12 team members',due:'Due in 3 days',priority:'Normal',description:'Approve a limited pilot of the procurement copilot for twelve team members using the approved procurement knowledge base.',fields:{'Pilot duration':'30 days','Data scope':'Approved procurement documents','Security review':'Completed'},status:'Pending'},
{id:'PO-2026-0931',title:'Office furniture procurement',app:0,name:'Yousef Ahmed',department:'Administration',amount:'QAR 42,750',due:'Due in 3 days',priority:'Normal',description:'Furniture for the new project management office, including desks, chairs and meeting tables.',fields:{'Vendor':'Al Mana Interiors','Cost center':'ADM-1020','Budget available':'QAR 75,000'},status:'Pending'},
{id:'HR-2026-0214',title:'Learning & development request',app:1,name:'Noor Mohammed',department:'Finance',amount:'QAR 4,800',due:'Due in 4 days',priority:'Normal',description:'Enrollment in a financial planning and analysis certification program.',fields:{'Course':'Financial Planning & Analysis','Provider':'Corporate Finance Institute','Duration':'6 weeks'},status:'Pending'}];
